/*
 * Auto-generated by ./makeconfig.
 * Changes are lost when ./makeconfig is run again.
 */

/* checked if a hello world program can be built */
#pragma once
#define _GNU_SOURCE

/* checked for <alloca.h> */
#define HAVE_ALLOCA_H
/* checked for alloca() */
#define HAVE_ALLOCA
/* checked for ssize_t */
#define HAVE_SSIZE_T
/* checked for snprintf() */
#define HAVE_SNPRINTF
/* checked for fchdir() */
#define HAVE_FCHDIR
/* checked for mmap() */
#define HAVE_MMAP
/* checked for mremap() */
#define HAVE_MREMAP
/* checked for iconv functionality */
#define HAVE_ICONV
/* checked for wctype functionality */
#define HAVE_WCTYPE_H
/* checked for wcwidth()  */
#define HAVE_WCWIDTH
/* checked for mbtowc() */
#define HAVE_MBTOWC
/* checked for setlocale() */
#define HAVE_SETLOCALE
/* checked for nl_langinfo() */
#define HAVE_NL_LANGINFO
/* checked for mkstemp() */
#define HAVE_MKSTEMP
/* checked for fpathconf() */
#define HAVE_FPATHCONF
/* checked for wordexp() */
#define HAVE_WORDEXP
/* checked for <arpa/inet.h> */
#define HAVE_ARPA_INET_H
/* checked for socket functionality in libc */
#define HAVE_SOCKETS
/* checked for IPv6 functionality getaddrinfo */
#define HAVE_GETADDRINFO
/* checked for IPv6 functionality getnameinfo */
#define HAVE_GETNAMEINFO
#define HAVE_IPv6_FUNCS
#define USE_SSL
#define USE_OPENSSL
#define HAVE_STACK_OF
//#define USE_GSSAPI
